// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package stocks

import (
	"context"
)

type Querier interface {
	AddToAvailableStock(ctx context.Context, arg AddToAvailableStockParams) error
	DecrementAvailableStock(ctx context.Context, arg DecrementAvailableStockParams) (int64, error)
	GetAvailableStockAmount(ctx context.Context, sku int32) (int32, error)
	UpsertAvailableStock(ctx context.Context, arg UpsertAvailableStockParams) error
}

var _ Querier = (*Queries)(nil)
