// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package stocks

import (
	"context"
)

const addToAvailableStock = `-- name: AddToAvailableStock :exec
INSERT INTO loms.available_stocks AS a (sku, amount)
VALUES ($1, $2)
ON CONFLICT (sku) DO UPDATE
    SET amount = a.amount + EXCLUDED.amount
`

type AddToAvailableStockParams struct {
	Sku    int32 `json:"sku"`
	Amount int32 `json:"amount"`
}

func (q *Queries) AddToAvailableStock(ctx context.Context, arg AddToAvailableStockParams) error {
	_, err := q.db.Exec(ctx, addToAvailableStock, arg.Sku, arg.Amount)
	return err
}

const decrementAvailableStock = `-- name: DecrementAvailableStock :execrows
UPDATE loms.available_stocks
SET amount = amount - $2
WHERE sku = $1
  AND amount >= $2
`

type DecrementAvailableStockParams struct {
	Sku    int32 `json:"sku"`
	Amount int32 `json:"amount"`
}

func (q *Queries) DecrementAvailableStock(ctx context.Context, arg DecrementAvailableStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementAvailableStock, arg.Sku, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAvailableStockAmount = `-- name: GetAvailableStockAmount :one
SELECT COALESCE(
               (SELECT amount
                FROM loms.available_stocks
                WHERE sku = $1),
               0
       )::integer AS amount
`

func (q *Queries) GetAvailableStockAmount(ctx context.Context, sku int32) (int32, error) {
	row := q.db.QueryRow(ctx, getAvailableStockAmount, sku)
	var amount int32
	err := row.Scan(&amount)
	return amount, err
}

const upsertAvailableStock = `-- name: UpsertAvailableStock :exec
INSERT INTO loms.available_stocks (sku, amount)
VALUES ($1, $2)
ON CONFLICT (sku) DO UPDATE SET amount = EXCLUDED.amount
`

type UpsertAvailableStockParams struct {
	Sku    int32 `json:"sku"`
	Amount int32 `json:"amount"`
}

func (q *Queries) UpsertAvailableStock(ctx context.Context, arg UpsertAvailableStockParams) error {
	_, err := q.db.Exec(ctx, upsertAvailableStock, arg.Sku, arg.Amount)
	return err
}
