// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package order

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, created_at, updated_at
FROM loms.orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO loms.orders (id, user_id, status)
VALUES ($1, $2, $3::loms.order_status)
RETURNING id, user_id, status, created_at, updated_at
`

type InsertOrderParams struct {
	ID     int64           `json:"id"`
	UserID int64           `json:"user_id"`
	Status LomsOrderStatus `json:"status"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, insertOrder, arg.ID, arg.UserID, arg.Status)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO loms.order_info (order_id, sku, amount)
VALUES ($1, $2, $3)
`

type InsertOrderItemParams struct {
	OrderID int64 `json:"order_id"`
	Sku     int32 `json:"sku"`
	Amount  int32 `json:"amount"`
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem, arg.OrderID, arg.Sku, arg.Amount)
	return err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT sku, amount
FROM loms.order_info
WHERE order_id = $1
ORDER BY sku
`

type ListOrderItemsByOrderIDRow struct {
	Sku    int32 `json:"sku"`
	Amount int32 `json:"amount"`
}

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID int64) ([]ListOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsByOrderIDRow
	for rows.Next() {
		var i ListOrderItemsByOrderIDRow
		if err := rows.Scan(&i.Sku, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderStatus = `-- name: SetOrderStatus :exec
UPDATE loms.orders
SET status     = $1::loms.order_status,
    updated_at = $2
WHERE id = $3
`

type SetOrderStatusParams struct {
	Status    LomsOrderStatus    `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        int64              `json:"id"`
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
